name: Deploy Cloud Function to GCP

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup gcloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy Cloud Function
      run: |
        echo "username: \"${{ secrets.EMAIL_USERNAME }}\"" > .env.yaml
        echo "password: \"${{ secrets.EMAIL_PASSWORD }}\"" >> .env.yaml
        echo "sender: \"${{ secrets.EMAIL_SENDER }}\"" >> .env.yaml
        echo "recipients: \"${{ secrets.EMAIL_RECIPIENTS }}\"" >> .env.yaml
        echo "SMTP: smtp.gmail.com" >> .env.yaml

        gcloud functions deploy ${{ secrets.GCP_FUNCTION_NAME }} \
          --runtime python310 \
          --region ${{ secrets.GCP_REGION }} \
          --entry-point notify_email \
          --trigger-topic cloudrun-deploy-topic \
          --env-vars-file .env.yaml
